### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by masterchi3f** [DerYeger/destiny-power-calculator#1]
that project sounds quite cool to me :D
finished it? Write a README.md and show us how to use it :P

**Comment by DerYeger** [comment]
I'm no longer developing this project, but it is in a functional state.
Usage is pretty straight forward. Build the project with the Gradle build task or create an .exe if you're on Windows using the Gradle publish task.
The app itself requires you to enter the gear levels of your character. It will then highlight gear that can be upgraded with on-level drops accross your characters for an overall power increase. This helps saving powerful and pinnacle rewards for the perfect moment.
However, I recommend checking out my [web app version](https://github.com/DerYeger/destiny-leveling-utility) of destiny-power-calculator instead.
